// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnKjUnXRIi3amhtB-XpXd3cqc-XAuB7vA',
    appId: '1:707520837275:web:b87cff21b043c841b9383e',
    messagingSenderId: '707520837275',
    projectId: 'handlenoe',
    authDomain: 'handlenoe.firebaseapp.com',
    storageBucket: 'handlenoe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-cmQN6tUzME3pGGChK2q-sbgnfq5lCPI',
    appId: '1:707520837275:android:2187b72433c806d8b9383e',
    messagingSenderId: '707520837275',
    projectId: 'handlenoe',
    storageBucket: 'handlenoe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaOMLhr92x6hPkGDW9IFdNUdE9noJIxjg',
    appId: '1:707520837275:ios:d21e5fa82d4f61dcb9383e',
    messagingSenderId: '707520837275',
    projectId: 'handlenoe',
    storageBucket: 'handlenoe.appspot.com',
    iosBundleId: 'com.example.handlenoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaOMLhr92x6hPkGDW9IFdNUdE9noJIxjg',
    appId: '1:707520837275:ios:d21e5fa82d4f61dcb9383e',
    messagingSenderId: '707520837275',
    projectId: 'handlenoe',
    storageBucket: 'handlenoe.appspot.com',
    iosBundleId: 'com.example.handlenoe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnKjUnXRIi3amhtB-XpXd3cqc-XAuB7vA',
    appId: '1:707520837275:web:45607cbcd5074222b9383e',
    messagingSenderId: '707520837275',
    projectId: 'handlenoe',
    authDomain: 'handlenoe.firebaseapp.com',
    storageBucket: 'handlenoe.appspot.com',
  );
}
